// resources/assets/js/components/PitchButton.jsx
import React, {useState} from 'react';
import Button from "./inputs/Button";
import {start} from "tone";
import Icon from "./Icon";

const PitchButton = ({ instrument, note, octave = 4, withIcon = true, variant="primary", size = "md", className, labelClassName = 'w-4' }) => {
    const pitch = (note.length > 1 ? note.slice(0, 2) : note) + octave.toString();

    function play(e) {
        e.stopPropagation();
        e.preventDefault();
        document.addEventListener('mouseup', stop);
        document.addEventListener('touchend', stop);

        start();
        instrument.instrument.triggerAttack(pitch);
    }

    function stop(e) {
        e.stopPropagation();
        e.preventDefault();
        document.removeEventListener('mouseup', stop);
        document.removeEventListener('touchend', stop);

        instrument.instrument.triggerRelease();
    }

    return (
        <Button onMouseDown={play} onMouseUp={stop} onTouchStart={play} onTouchEnd={stop} variant={variant} size={size} className={className}>
            {withIcon && <Icon icon="play" />}
            <span className={labelClassName}>{note}</span>
        </Button>
    );
}

export default PitchButton;

// resources/assets/js/components/PitchButton.vue
<template>
    <button class="pitch btn btn-secondary btn-sm" v-on:mousedown="play" v-on:mouseup="stop" v-on:touchstart="play" v-on:touchend="stop">
        <i class="fa fa-play mr-1"></i> <span class="key">{{ note }}</span>
    </button>
</template>

<script>
import { start, Synth } from 'tone';
export default {
    name: "PitchButton",
    props: {
        note: {
            type: String,
            required: true
        },
        octave: {
            type: Number,
            default: 4
        }
    },
    created() {
        this.synth = new Synth().toDestination()
    },
    computed: {
        pitch() {
            return this.note + this.octave.toString();
        }
    },
    methods: {
        play(e) {
            e.stopPropagation();
            e.preventDefault();
            document.addEventListener('mouseup', this.stop);
            document.addEventListener('touchend', this.stop);

            start();
            this.synth.triggerAttack( this.pitch );
        },
        stop(e) {
            e.stopPropagation();
            e.preventDefault();
            document.removeEventListener('mouseup', this.stop);
            document.removeEventListener('touchend', this.stop);

            this.synth.triggerRelease();
        }
    }
}
</script>

<style scoped>
button {
    min-width: 60px;
}
</style>
